### ISSUE TITLE
Prebuilds don't work anymore

### ISSUE THREAD

**Issue by cdfa** [complyue/tour#2]
When you open the repo in a GitPod workspace it does not use a prebuild.
Configuring prebuilds in `.gitpod.yml` seems to be deprecated.
A yaml validation error in `.gitpod.yml` says: `Please use the Project Settings to configure prebuilds`.

**Comment by complyue** [comment]
Simply removed that block of cfg as not that critical, hope there's no harm.

Please reopen this if the removal hurts anyway.
